# Generated by Django 6.0.6 on 2026-06-06 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(default="Beispielgebäude", max_length=200),
                ),
                ("nrf_total", models.FloatField(default=0)),
                ("nrf_tg", models.FloatField(default=0)),
                ("nrf_heated", models.FloatField(default=0)),
                ("an_geg", models.FloatField(default=0)),
                ("building_type", models.CharField(max_length=200)),
                ("energy_standard", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("heating", models.CharField(max_length=200)),
                ("ventilation", models.CharField(max_length=200)),
                ("pv_area", models.FloatField(default=0)),
                ("battery_storage", models.CharField(default="nein", max_length=20)),
                ("qng_level", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scenarios",
                        to="qngapp.building",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ac_qp_rel", models.FloatField(default=0)),
                ("ac_gwp_rel", models.FloatField(default=0)),
                ("qp_limit", models.FloatField(default=0)),
                ("gwp_limit", models.FloatField(default=0)),
                ("qp_status", models.CharField(max_length=50)),
                ("gwp_status", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "scenario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="qngapp.scenario",
                    ),
                ),
            ],
        ),
    ]
