# Generated by Django 6.0.6 on 2026-06-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("qngapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="building_category",
            field=models.CharField(default="Mehrfamilienhaus", max_length=100),
        ),
    ]
